orukRed/tyranosyntax

CHANGELOG.md, package-lock.json, package.json
=> ver0.13.0で拡張機能が正常に動作しない問題の修正

tsconfig.json
https://github.com/orukRed/tyranosyntax/issues/162
=> `tsconfig` をフォーマット

eslint.config.mjs, package-lock.json, package.json, src/subscriptions/TyranoFlowchart.ts
=> フローチャートの型付け

.prettierignore, .vscode/extensions.json, .vscode/launch.json, .vscode/tasks.json, language-configuration.json, package.json
各種jsonファイルへフォーマッタ適用
- .vscode/*.json
- package.json の contributes
- language-configuration*.json
=> フォーマッタ適用 #162

CHANGELOG.md, package.json, src/InformationWorkSpace.ts
https://github.com/orukRed/tyranosyntax/issues/178
再現できてないのでいったんドラフトで。
問題なさそう、かつ動作確認OKならマージしてアプデ
=> fix:.gitフォルダを無視するように修正

CHANGELOG.md, README.md, package.json, src/subscriptions/TyranoCompletionItemProvider.ts
=> #での補完でnameではなくjnameの値が出力されてしまう問題の修正 #187

CHANGELOG.md, package.json, src/subscriptions/TyranoCompletionItemProvider.ts
=> #での補完時、行頭に#がある場合にしか補完が効かない

src/subscriptions/TyranoJumpProvider.ts
TyranoJumpProvider` の型付けとリファクタリング
=> refactor(type):`TyranoJumpProvider` のタイピング

CHANGELOG.md, package.json, src/subscriptions/TyranoJumpProvider.ts
=> scenarioフォルダの中に再帰的なフォルダを置き、storageを指定しない場合TyranoJumpProviderが起動しなくなる

CHANGELOG.md, README.md, Tooltip/en.tyrano.tooltip.json, Tooltip/tyrano.Tooltip.json, package.json, snippet/en.tyrano.snippet.json, snippet/tyrano.snippet.json, src/InformationExtension.ts, src/InformationWorkSpace.ts, src/subscriptions/TyranoHoverProvider.ts
Fixes #180
後で日本語、英語版ともにjsonに更新ないかどうか調べる
更新必要ならしておくこと
=> タグ補完、ホバー用のjsonの英語版追加

CHANGELOG.md, README.md, Tooltip/en.tyrano.tooltip.json, package.json, snippet/en.tyrano.snippet.json, src/subscriptions/TyranoDiagnostic.ts
=> 診断機能のONOFFを切り替えられるようにしたい

src/subscriptions/TyranoDiagnostic.ts
=> 診断機能を実行する条件が反対なのを修正

eslint.config.mjs
=> test_projectフォルダをeslintの除外フォルダにしたい

CHANGELOG.md, README.md, package.json, src/subscriptions/TyranoPreview.ts, test_project/data/scenario/initialize.ks
=> その場プレビューのpreprocessファイルを相対パスでも指定できるようにしたい

CHANGELOG.md, package.json, preview/preview_js.js
=> その場プレビューで、chara_layerで定義したパーツが多すぎるとchara_partで止まる？

CHANGELOG.md, package.json, preview/preview_js.js, src/subscriptions/TyranoPreview.ts
=> その場プレビューで、[p][ct][er]がないファイルを読み込んだ時の挙動について

CHANGELOG.md, package.json, src/extension.ts, src/subscriptions/TyranoCompletionItemProvider.ts, src/subscriptions/TyranoCreateTagByShortcutKey.ts, src/subscriptions/TyranoDiagnostic.ts, src/test/suite/subscriptions/TyranoCreateTagByShortcutKey.test.ts
=> storageパラメータで指定したファイルが存在しないときにエラーを出したい

CHANGELOG.md, flowchart/flowchart.html, package.json
Fixes #250
拡大機能追加
jump系のタグがない場合にその旨を表示
=> フローチャートに拡大機能をつけたい

CHANGELOG.md, package.json, src/subscriptions/TyranoDiagnostic.ts
=> 1.4.0で追加したエラー機能で特定の場合にエラーを防ぎたい

CHANGELOG.md, package.json, src/subscriptions/TyranoOutlineProvider.ts, test_project/data/scenario/test.ks
=> //から始まる行もコメント用のアウトラインに表示したい

CHANGELOG.md, package.json, src/subscriptions/TyranoPreview.ts
=> ティラノv6以降でその場プレビューが起動していない
